# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Diny < Formula
  desc "🦕 Generate meaningful commit messages from git diff"
  homepage "https://github.com/dinoDanic/diny"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dinoDanic/diny/releases/download/v0.2.0/diny_Darwin_x86_64.tar.gz"
      sha256 "46b46d2e5a7213b9a18695ab46d64352d3c929bce1f30e43a51732076a4ec0c1"

      def install
        bin.install "diny"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dinoDanic/diny/releases/download/v0.2.0/diny_Darwin_arm64.tar.gz"
      sha256 "821da68fc7a506b6613c8f122255db9b096499cb84f43953fd7040b6c03a02f0"

      def install
        bin.install "diny"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dinoDanic/diny/releases/download/v0.2.0/diny_Linux_x86_64.tar.gz"
      sha256 "410cfb3deb5f9346c38289fbc43832025a3f13396483547a53850a416a029dcb"
      def install
        bin.install "diny"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dinoDanic/diny/releases/download/v0.2.0/diny_Linux_arm64.tar.gz"
      sha256 "63c5e0c14fd82e01830cc8aa0bf8b964bcb27c43a690da2a7d2af7f37ddb64a5"
      def install
        bin.install "diny"
      end
    end
  end

  test do
    system "#{bin}/diny --version"
  end
end
